name: 17 - 3 Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to ping'
        default: 'https://www.google.com'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
